<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17885" started-at="2018-10-24T00:39:07Z" finished-at="2018-10-24T00:39:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17885" started-at="2018-10-24T00:39:07Z" finished-at="2018-10-24T00:39:25Z">
      <class name="E2EFramework.ValidateTitle">
        <test-method status="PASS" signature="initilize()[pri:0, instance:E2EFramework.ValidateTitle@5419f379]" name="initilize" is-config="true" duration-ms="3479" started-at="2018-10-23T20:39:07Z" finished-at="2018-10-23T20:39:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilize -->
        <test-method status="FAIL" signature="basePageNavigation()[pri:0, instance:E2EFramework.ValidateTitle@5419f379]" name="basePageNavigation" duration-ms="12288" started-at="2018-10-23T20:39:11Z" finished-at="2018-10-23T20:39:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Featured Courses123] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Featured Courses123] but found [FEATURED COURSES]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at E2EFramework.ValidateTitle.basePageNavigation(ValidateTitle.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basePageNavigation -->
        <test-method status="PASS" signature="driverclose()[pri:0, instance:E2EFramework.ValidateTitle@5419f379]" name="driverclose" is-config="true" duration-ms="2102" started-at="2018-10-23T20:39:23Z" finished-at="2018-10-23T20:39:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverclose -->
      </class> <!-- E2EFramework.ValidateTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
